### ISSUE TITLE
レイアウトされたTextに絵文字が表示されない

### ISSUE THREAD

**Issue by JINZO631** [sassembla/LayouTaro#4]
# 再現手順

1. [TMP Settings.asset](https://github.com/sassembla/LayouTaro/blob/master/Assets/TextMesh%20Pro/Resources/TMP%20Settings.asset)の`Default Sprite Asset`に[EmojiOne.asset](https://github.com/sassembla/LayouTaro/blob/master/Assets/TextMesh%20Pro/Resources/Sprite%20Assets/EmojiOne.asset)を設定する。
![image](https://user-images.githubusercontent.com/9525135/78128183-78233380-7450-11ea-9163-79a6add350cb.png)

2. [LayouTaroSample.cs](https://github.com/sassembla/LayouTaro/blob/master/Assets/Sample/LayouTaroSample.cs#L31)の31行目を`\U0001F60A`(😊)を追加したものに書き換える。

```            TextElement.GO("hannin is yasu! this is public problem! gooooooooooooood"),```
から
```            TextElement.GO("hannin is yasu!\U0001F60A this is public problem! gooooooooooooood"),```
へ
![image](https://user-images.githubusercontent.com/9525135/78129233-35faf180-7452-11ea-90b4-de0eca571f9b.png)

3. [MiyamasuTestIgnite.cs](https://github.com/sassembla/LayouTaro/blob/master/Assets/MiyamasuTestRunner/Runtime/MiyamasuTestIgniter.cs)の`[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]`をコメントアウトする。
![image](https://user-images.githubusercontent.com/9525135/78129467-9e49d300-7452-11ea-8d1e-965d68d4c29b.png)

3. [sample](https://github.com/sassembla/LayouTaro/blob/master/Assets/sample.unity)シーンを実行する。
![image](https://user-images.githubusercontent.com/9525135/78129537-b9b4de00-7452-11ea-94d1-99ff285381de.png)

`\U0001F60A`(😊)が表示されるであろう部分が空白な状態で表示される。

# 期待していた表示

![image](https://user-images.githubusercontent.com/9525135/78129681-ecf76d00-7452-11ea-92da-4438e27de305.png)

この見た目は上記再現手順のあとに`Canvas/Box(Clone)/Text(Clone)/TMP SubMeshUI [TextMeshPro/Sprite`のRectTransformをUnityEditor上でComponentMenuからResetして下の画像の内容に変更したものです。
![image](https://user-images.githubusercontent.com/9525135/78130397-35635a80-7454-11ea-9064-48a0f209a135.png)

**Comment by sassembla** [comment]
The Emoji feature is implemented at 8ab7d1e7ec0a785dc80eeffd0ff2fb607fb3d657. please use this!
